[project]
name = "randselect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yun Zhou", email = "yun.zhou@mcmaster.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.64.0",
]

[project.scripts]
randselect = "randselect.cli:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
